### ISSUE TITLE
min and max ?

### ISSUE THREAD

**Issue by yanzixiang** [jorgen/json_struct#26]
```
#if defined(min) || defined(max)

#error min or max macro is defined. Make sure these are not defined before including json_struct.h.\
 Use "#define NOMINMAX 1" before including Windows.h
#endif
```

I have #define NOMINMAX 1,
but I can NOT compile this either,

using vs 2022 and qt5.
How can I find where are minx and max macro is defined and disable it ?

**Comment by jorgen** [comment]
You can add /DNOMINMAX=1 as a compiler flag or you can include json_struct.h. 
Or you define #define NOMINMAX 1 at the top of the cpp files it should also work. 
You could include json_struct.h before you include Qt or any other header. I had a quick look at the Qt headers and it seems they are defining NOMINMAX before including Windows.h.

**Comment by jorgen** [comment]
- Im closing this issue since I have no better idea than the what is mentioned in the previous comment
