### ISSUE TITLE
GNUInstallDirs is required for CMAKE_INSTALL_DATAROOTDIR

### ISSUE THREAD

**Issue by retifrav** [jorgen/json_struct#29]
You have commented out `#include(GNUInstallDirs)` in the root `CMakeLists.txt`, but it actually is required for `CMAKE_INSTALL_DATAROOTDIR`, otherwise it defaults to `/`, at least it does so in my builds (*on Windows, GNU/Linux and Mac OS*):

``` sh
$ mkdir build && cd $_
$ cmake -DCMAKE_INSTALL_PREFIX="../install" -DJSON_STRUCT_OPT_BUILD_BENCHMARKS=0 -DJSON_STRUCT_OPT_BUILD_EXAMPLES=0 -DJSON_STRUCT_OPT_BUILD_TESTS=0 ..
$ cmake --build . --target install --config Release
```
```
-- Installing: D:/code/json-struct/install/lib/cmake/json_struct/json_structConfigVersion.cmake
-- Installing: D:/code/json-struct/install/lib/cmake/json_struct/json_structConfig.cmake
-- Installing: D:/code/json-struct/install/./include
-- Installing: D:/code/json-struct/install/./include/json_struct.h
-- Installing: D:/code/json-struct/install/./include/json_struct_diff.h
-- Installing: /json_struct/package.xml
```

And if I uncomment `include(GNUInstallDirs)`, then `CMAKE_INSTALL_DATAROOTDIR` gets a proper value and installation goes correctly:

```
...
-- Installing: D:/code/json-struct/install/share/json_struct/package.xml
```

So, I am not sure why you commented it out, maybe there was a good reason, but I decided to let you know about this, just in case.

While we are at it, perhaps you'd want to do something with `.` destination for installing `include`. It certainly works as it is, but doesn't look entirely correct (*`D:/code/json-struct/install/./include/json_struct.h`*).

**Comment by jorgen** [comment]
Thank you. I'm a bit unavailable for a few days, but will fix this once I'm home.

**Comment by jrmelsha** [comment]
Good to uncomment that! I need to do a PR from my fork when I get a chance.. Sorry about that!

**Comment by retifrav** [comment]
> moved json_struct.h into a sub folder so its now under D:/code/json-struct/install/include/json_struct/json_struct.h

I think this is a good idea, I prefer this approach too.
