### ISSUE TITLE
Cannot parse std::tuple<bool>

### ISSUE THREAD

**Issue by guycook** [jorgen/json_struct#42]
On MSVC, I'm unable parse fields like `"member": [true]` to a type `std::tuple<bool> member`. A minimal example is below
```c++
#include <iostream>
#include "json_struct.h"

struct TestInt {
  std::tuple<int32_t> member;
  JS_OBJ(member);
};

struct TestBool {
  std::tuple<bool> member;
  JS_OBJ(member);
};

int main(int argc, char** argv) {
  TestInt tiStruct;
  JS::ParseContext intContext(R"({ "member": [5] })");
  if (intContext.parseTo(tiStruct) == JS::Error::NoError) {
    std::cout << "Success, member is: " << std::get<0>(tiStruct.member) << std::endl;
  }
  else {
    std::cout << intContext.makeErrorString();
  }

  TestBool tbStruct;
  JS::ParseContext boolContext(R"({ "member": [true] })");
  if (boolContext.parseTo(tbStruct) == JS::Error::NoError) {
    std::cout << "Success, member is: " << std::get<0>(tbStruct.member) << std::endl;
  }
  else {
    std::cout << boolContext.makeErrorString();
  }
}
```

Output:
```
Success, member is: 5
Error ExpectedDelimiter:
{ "member": [true] }
                  ^
```

I'm not sure what the cause here is, all I can say from current investigation is that single item tuples of other basic types (number/string) still work, and tuples involving bools + other types work, e.g. `std::tuple<bool, int>` will parse fine if given `[true, 2]`

**Comment by jorgen** [comment]
Hi and thank you for your interest in json_struct. There was an error in a lookup table, making the end of token be the ] and not the e. Its fixed in the latest commit.

**Comment by guycook** [comment]
Thanks for the quick resolution, can confirm this fixes the problem in my project as well as the test case. json_struct has been great so far, cheers!
