### ISSUE TITLE
Invalid memory access when parsing message

### ISSUE THREAD

**Issue by noodlecollie** [jorgen/json_struct#44]
This bug was discovered when we accidentally parsed a gateway error page as a JSON response from an API. I wasn't expecting the parsing to succeed, but the parsing process actually caused a crash.

I created a minimal reproducible example, below:

```cpp
#include <iostream>
#include "json_struct.h"

static const char* const MESSAGE =
	"<html>\r\n"
	"<head><title>400 Bad Request</title></head>\r\n"
	"<body>\r\n"
	"<center><h1>400 Bad Request</h1></center>\r\n"
	"<hr><center>cloudflare</center>\r\n"
	"</body>\r\n"
	"</html>\r\n";

int main(int*, char**)
{
	std::cout << "Parsing message" << std::endl;

	JS::ParseContext context(MESSAGE);
	JS::Map outMap;
	JS::Error errror = context.parseTo(outMap);

	std::cout << "Error: " << context.makeErrorString() << std::endl;

	return 0;
}
```

When attempting to parse this, I get output that begins:

```
Parsing message
Error: Error EncounteredIllegalChar:
HHtHH;rHHtgHH#rHHtOHHrLHt7HD$HA...
```

After inspection in the debugger, the issue appears to be an unsigned underflow on line 1740:

```cpp
for (cursor_back = real_cursor_index - 1; cursor_back > stop_back; cursor_back--)
```

Here, because the first character of the input was not valid, `real_cursor_index` is `0`, so subtracting `1` underflows the index.

**Comment by jorgen** [comment]
Hi! Thank you for your detailed bugreport. This is fixed now.
