### ISSUE TITLE
Brilliant!

### ISSUE THREAD

**Issue by DBJDBJ** [jorgen/json_struct#5]
## Can we now get rid of `std::` lib, please?

**Comment by jorgen** [comment]
Yeah, this is a good request! I'm fixing the float -> string and string -> float (float meaning float and double). After that I can add a preprocessor define to not include any std headers.

**Comment by DBJDBJ** [comment]
I am thinking, perhaps you might use [Martin Moenes](https://github.com/martinmoene) std replacements?
I would certainly start replacing `std::string` first. We have included just a plain vanilla vector we found on the GitHub and now using dbj::vector<char> instead of `std::string` ... although [Vivkin has a pretty decent vector](https://github.com/vivkin/jzon) 

I would be glad to help but am completely spent on P2192R0 ...

**Comment by oysteinmyrmo** [comment]
Side note: It is trivial to remove `std::string` from the diff header as well, but the diff tests must also be updated after the `std::string` diff constructors are removed.

**Comment by DBJDBJ** [comment]
I understand. what do you plan to replace `std:string` with? 

Let me "go on the limb" .. We here (for 1+ year now) have done the following:

1. include home grown vector
2. do something like: `using my_string = my_vector<char>`
3. have  `struct my_string_services` with various static methods to construct `my_string` instances and do whatever else might be required that involves `my_string` ... 

Just then I would modify this repo, including diff header and diff test ...  I am sure I have missed something this repo specific.

**Comment by jorgen** [comment]
After reviewing this issue, I have decided not to give it any priority. It would be nice. Have to create a std::string and a std::vector implementations. And then the typehandlers for all the std stuff could be ifdeffed. But I will focus on other things for the foreseeable future. Patches are welcome.

**Comment by DBJDBJ** [comment]
In the meantime, I worketh in a distant galaxy. But accidentally I created  [EASTL2020CORE](https://github.com/DBJDBJ/EASTL2020CORE), which indeed works etc, etc ... Yes in theory and in my galaxy it can be used. But to package it such that other galaxies can use it will require time and effort that we simply do not have. HTH & KR
