### ISSUE TITLE
serial a class' private member

### ISSUE THREAD

**Issue by yanzixiang** [jorgen/json_struct#56]
i try to serial a class like this,
```c++
class a{
public:
  std::string b;
}

JS_OBJ_EXT(a,b);
```

```c++
a my_a;
auto json_string_a = JS::serializeStruct(my_a);
```
it works fine.

but when i add a private member c
```c++
class a{
public:
  std::string b;
private:
  std::string c;
}

JS_OBJ_EXT(a,b,c);
```

the complier says it can NOT access private member.
so, how can i make it work again ?

**Comment by jorgen** [comment]
Yes, the serializxer and parser needs access to the members. The parser and serializer will use member pointers declared by the JS_OBJ_EXT macro. There is however, a trick. If you use a "internal" JS_OBJ structure and make that public, then the serializer and parser can use that to access the members. Check out this godbolt that shows this:
https://godbolt.org/z/7WznYTPn8

**Comment by jorgen** [comment]
This worked for me, but the typehandler was not generating the correct data. I made a typehandler that handles the vec3 as a json array and not an object. Does this work for you? 
https://godbolt.org/z/h5oa5hsY7 :

namespace JS {
    template<>
    struct TypeHandler<simCore::Vec3>
    {
    public:
        static inline Error to(simCore::Vec3& to_type, ParseContext& context)
        {
            double array[3];
            auto err = TypeHandler<double[3]>::to(array, context);
            if (err != Error::NoError)
                return err;

            to_type.setX(array[0]);
            to_type.setY(array[1]);
            to_type.setZ(array[2]);
            return Error::NoError;
        }

        static void from(const simCore::Vec3& from_type, Token& token, Serializer& serializer)
        {
            double array[3];
            array[0] = from_type.x();
            array[1] = from_type.y();
            array[2] = from_type.z();
            TypeHandler<double[3]>::from(array, token, serializer);
        }
    };
}

**Comment by yanzixiang** [comment]
YES,THANKS.

> This worked for me, but the typehandler was not generating the correct data. I made a typehandler that handles the vec3 as a json array and not an object. Does this work for you? [Godbolt](https://godbolt.org/z/h5oa5hsY7)
> 
> ```
> namespace JS {
>     template<>
>     struct TypeHandler<simCore::Vec3>
>     {
>     public:
>         static inline Error to(simCore::Vec3& to_type, ParseContext& context)
>         {
>             double array[3];
>             auto err = TypeHandler<double[3]>::to(array, context);
>             if (err != Error::NoError)
>                 return err;
> 
>             to_type.setX(array[0]);
>             to_type.setY(array[1]);
>             to_type.setZ(array[2]);
>             return Error::NoError;
>         }
> 
>         static void from(const simCore::Vec3& from_type, Token& token, Serializer& serializer)
>         {
>             double array[3];
>             array[0] = from_type.x();
>             array[1] = from_type.y();
>             array[2] = from_type.z();
>             TypeHandler<double[3]>::from(array, token, serializer);
>         }
>     };
> }
> ```
