### ISSUE TITLE
how to deal with std::string in TypeHandler

### ISSUE THREAD

**Issue by yanzixiang** [jorgen/json_struct#58]
hi there,
i need to deal with a class 
```c++
class a{
public:
    osgEarth::Config config;
}
```
and osgEarth::config is defined here like this
https://github.com/gwaldron/osgearth/blob/a983110dac617406be4983180e7e8914f57fc3af/src/osgEarth/Config#L128

```c++
        /** Populate this object from a JSON string. */
        bool fromJSON(const std::string& json);
        static Config readJSON(const std::string& json);
```

how can i use json_struct to deal class a ?

**Comment by jorgen** [comment]
Hey, I made a short example here: https://godbolt.org/z/hs56b6Wv

Can you please verify that it solves your problem?

**Comment by jorgen** [comment]
I'm closing the issue since I have not gotten any feed back.
