### ISSUE TITLE
std::optional<std::vector<my_struct>> will cause program exit

### ISSUE THREAD

**Issue by ad-long** [jorgen/json_struct#8]
change from:
#ifdef JS_STD_OPTIONAL
/// \private
template <typename T>
struct TypeHandler<std::optional<T>>
{
public:
  static inline Error to(std::optional<T> &to_type, ParseContext &context)
  {
    to_type = {};
    return TypeHandler<T>::to(to_type.value(), context);
  }

  static inline void from(const std::optional<T> &opt, Token &token, Serializer &serializer)
  {
    if (opt.has_value())
      TypeHandler<T>::from(opt.value(), token, serializer);
  }
};
#endif

to:
#ifdef JS_STD_OPTIONAL
/// \private
template <typename T>
struct TypeHandler<std::optional<T>>
{
public:
  static inline Error to(std::optional<T> &to_type, ParseContext &context)
  {
    to_type = T();
    return TypeHandler<T>::to(to_type.value(), context);
  }

  static inline void from(const std::optional<T> &opt, Token &token, Serializer &serializer)
  {
    if (opt.has_value())
      TypeHandler<T>::from(opt.value(), token, serializer);
  }
};
#endif

will fix the bug

**Comment by jorgen** [comment]
Hi, thank you for reporting this!
Ok, there was an issue with the unit test, so it didn't test the deserialisation code!
I just pushed a26d21d48220815b0b3216aaf1c66b0928f5bf49. I ended up using the emplace function, but same same. I also improved the std::optional detection on msvc. Sorry about the trouble this has caused you!
