### ISSUE TITLE
float deserial error

### ISSUE THREAD

**Issue by ad-long** [jorgen/json_struct#9]
struct Json1
{
  float num1;
  double num2;

  JS_OBJECT(JS_MEMBER(num1), JS_MEMBER(num2));
};
const char json_data1[] = R"json(
	{
		"num1": 32587.403333333333333333,
		"num2": 32587.403333333333333333
	}
)json";

**Comment by jorgen** [comment]
Oh! Thats embarrassing! I will fix this tonight. Thank you for your bug report.

**Comment by jorgen** [comment]
Should be fixed now. Thank your for taking the time to file a bug report!
